const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const Babel = require(path.join(root, "vendor", "babel-standalone-7.29.0.min.js"));
const sources = [
  "icons.jsx",
  "controls.jsx",
  "editor.jsx",
  "preview.jsx",
  "api.js",
  "prompts.js",
  "jobs.jsx",
  "interview-data.js",
  "interview.jsx",
  "settings.jsx",
  "app.jsx",
];

const source = sources
  .map((filename) => {
    const fullPath = path.join(root, "src", filename);
    return `\n/* ===== ${filename} ===== */\n${fs.readFileSync(fullPath, "utf8")}`;
  })
  .join("\n");

const result = Babel.transform(source, {
  presets: ["react"],
  sourceType: "script",
  comments: true,
  compact: false,
  filename: "resume-editor.jsx",
});

const outputDir = path.join(root, "dist");
fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(
  path.join(outputDir, "app.js"),
  `/* Generated by scripts/build.js. Edit files in src/, then rebuild. */\n${result.code}\n`
);

console.log(`Built dist/app.js from ${sources.length} source files.`);
